wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.2
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.10.8
    start_time: 1673898470.503928
    t:
      1:
      - 1
      - 5
      - 41
      - 53
      - 55
      2:
      - 1
      - 5
      - 41
      - 53
      - 55
      3:
      - 16
      - 23
      4: 3.10.8
      5: 0.13.2
      8:
      - 5
backend:
  desc: null
  value: sp
batch_size:
  desc: null
  value: 128
central_epochs:
  desc: null
  value: 15
central_model_dir:
  desc: null
  value: /Users/vscheltjens/Documents/PhD/Projects/eicu-cl-req/central_training/
central_training:
  desc: null
  value: 0
central_wandb_project:
  desc: null
  value: recr_central_training
client_id_list:
  desc: null
  value: '[]'
client_num_in_total:
  desc: null
  value: 10
client_num_per_round:
  desc: null
  value: 3
client_optimizer:
  desc: null
  value: adamw
comm_round:
  desc: null
  value: 5
data_cache_dir:
  desc: null
  value: /Users/vscheltjens/Documents/PhD/Projects/eicu-cl-req/eICU_Data/
dataset:
  desc: null
  value: ICU
dist_model_dir:
  desc: null
  value: /Users/vscheltjens/Documents/PhD/Projects/eicu-cl-req/distributed_training/
div_weight:
  desc: null
  value: 0.5
dropout_prob:
  desc: null
  value: 0.05
enable_wandb:
  desc: null
  value: true
epochs:
  desc: null
  value: 2
federated_optimizer:
  desc: null
  value: FedAvg
frequency_of_the_test:
  desc: null
  value: 1
gpu_id:
  desc: null
  value: 0
hidden_dim:
  desc: null
  value: 32
input_dim:
  desc: null
  value: 128
inst_weight:
  desc: null
  value: 0.5
learning_rate:
  desc: null
  value: 0.005
local_rank:
  desc: null
  value: 0
log_file_dir:
  desc: null
  value: ./log
model:
  desc: null
  value: GRU
node_rank:
  desc: null
  value: 0
num_layers:
  desc: null
  value: 2
output_dim:
  desc: null
  value: 1
partition_alpha:
  desc: null
  value: 0.5
partition_method:
  desc: null
  value: hetero
random_seed:
  desc: null
  value: 0
rank:
  desc: null
  value: 0
recruitment:
  desc: null
  value: true
role:
  desc: null
  value: client
run_id:
  desc: null
  value: '0'
sys_perf_profiling:
  desc: null
  value: true
training_type:
  desc: null
  value: simulation
using_gpu:
  desc: null
  value: false
wandb_entity:
  desc: null
  value: vs-health
wandb_key:
  desc: null
  value: 8d579c56c0eda8929353aac11d399b96e5aa9e71
wandb_project:
  desc: null
  value: federated_gru_eicu
weight_decay:
  desc: null
  value: 0.005
worker_num:
  desc: null
  value: 3
yaml_config_file:
  desc: null
  value: /Users/vscheltjens/Documents/PhD/Projects/eicu-cl-req/distributed_training/config.yml
yaml_paths:
  desc: null
  value:
  - /Users/vscheltjens/Documents/PhD/Projects/eicu-cl-req/distributed_training/config.yml
