common_args:
  training_type: "simulation"
  random_seed: 0

data_args:
  dataset: "ICU"
  data_cache_dir: "/Users/vscheltjens/Documents/PhD/Projects/eicu-cl-req/eICU_Data/"
  partition_method: "hetero"
  partition_alpha: 0.5

model_args:
  model: "GRU"
  input_dim: 128
  hidden_dim: 32
  num_layers: 2
  output_dim: 1
  dropout_prob: 0.05
  dist_model_dir: "/Users/vscheltjens/Documents/PhD/Projects/eicu-cl-req/distributed_training/"
  central_model_dir: "/Users/vscheltjens/Documents/PhD/Projects/eicu-cl-req/central_training/"

train_args:
  federated_optimizer: "FedAvg"
  client_id_list: "[]"
  client_num_in_total: 5
  client_num_per_round: 3
  comm_round: 5
  epochs: 2
  batch_size: 128
  client_optimizer: adamw
  learning_rate: 0.005
  weight_decay: 0.005
  recruitment: False

central_training_args:
  central_epochs: 15

validation_args:
  frequency_of_the_test: 1

device_args:
  using_gpu: false
  gpu_id: 0

comm_args:
  backend: "sp"

tracking_args:
  log_file_dir: ./log
  enable_wandb: True
  wandb_key: 8d579c56c0eda8929353aac11d399b96e5aa9e71
  wandb_entity: vs-health
  wandb_project: federated_gru_eicu
  central_wandb_project: recr_central_training