wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.2
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.10.8
    start_time: 1673706265.74291
    t:
      1:
      - 1
      - 5
      - 41
      - 53
      - 55
      2:
      - 1
      - 5
      - 41
      - 53
      - 55
      3:
      - 16
      - 23
      4: 3.10.8
      5: 0.13.2
      8:
      - 5
central_training_args:
  desc: null
  value:
    central_epochs: 1
comm_args:
  desc: null
  value:
    backend: sp
common_args:
  desc: null
  value:
    random_seed: 0
    training_type: simulation
data_args:
  desc: null
  value:
    data_cache_dir: /Users/vscheltjens/Documents/PhD/Projects/eicu-cl-req/eICU_Data/
    dataset: ICU
    partition_alpha: 0.5
    partition_method: hetero
device_args:
  desc: null
  value:
    gpu_id: 0
    using_gpu: false
model_args:
  desc: null
  value:
    central_model_dir: /Users/vscheltjens/Documents/PhD/Projects/eicu-cl-req/central_training/
    dist_model_dir: /Users/vscheltjens/Documents/PhD/Projects/eicu-cl-req/distributed_training/
    dropout_prob: 0.05
    hidden_dim: 32
    input_dim: 128
    model: GRU
    num_layers: 2
    output_dim: 1
tracking_args:
  desc: null
  value:
    enable_wandb: true
    log_file_dir: ./log
    wandb_entity: vs-health
    wandb_key: 8d579c56c0eda8929353aac11d399b96e5aa9e71
    wandb_project: federated_gru_eicu
train_args:
  desc: null
  value:
    batch_size: 128
    client_id_list: '[]'
    client_num_in_total: 10
    client_num_per_round: 3
    client_optimizer: adamw
    comm_round: 5
    epochs: 2
    federated_optimizer: FedAvg
    learning_rate: 0.005
    weight_decay: 0.005
validation_args:
  desc: null
  value:
    frequency_of_the_test: 1
